[package]
name = "global_market"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.10"
line_intersection = "0.4.0"
geo = "0.4.13"
ordered-float = "1.0"